apiVersion: batch/v1
kind: Job
metadata:
  name: minio-client
spec:
  template:
    metadata:
      labels:
        app: minio-client
    spec:
      restartPolicy: OnFailure
      containers:
      - name: minio-client
        image: {{ .Values.mc.image }}
        command:
        - /bin/sh
        - -c
        - |
          sleep 10;
          until (/usr/bin/mc alias set myminio http://minio:9000 {{ .Values.minio.rootUser }} {{ .Values.minio.rootPassword }}); do echo '...waiting...' && sleep 1; done;
          /usr/bin/mc rm -r --force myminio/{{ .Values.minio.bucket }} || true;
          /usr/bin/mc mb myminio/{{ .Values.minio.bucket }};
          /usr/bin/mc anonymous set public myminio/{{ .Values.minio.bucket }};
          tail -f /dev/null